// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojguisyoagjjynojpwet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZ3Vpc3lvYWdqanlub2pwd2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5OTE5NTUsImV4cCI6MjA0OTU2Nzk1NX0.0ATJla6aUoOVmEfRDHzeeKcQOA7Qwpbw03sVchidEMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);